version: "2"
services:
  streaming-server:
    image: kmacmcfarlane/streaming-server
    build:
      context: "./"
      dockerfile: "Dockerfile"
    cpu_shares: 1024
    #mem_limit: 67108864
    #env_file:
    #  - ./gen/.env
    environment:
      CONTAINER_NAME: streaming-server
    container_name: "streaming-server"
    ports:
      - "1935:1935"
      - "80:80"
    volumes:
      - space:/mnt/space
    command: "/bin/bash -c 'echo hello && chmod -R 777 /mnt/space &&\
             mkdir -p /mnt/space/streaming-server/streams/hls || true &&\
             mkdir -p /mnt/space/streaming-server/streams/rtmp || true &&\
             echo starting nginx && nginx -g \"daemon off;\"'"
volumes:
  space:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/space
